import z, { ZodNumber, ZodNumberFormat, ZodString, ZodStringFormat, ZodType } from "zod/v4";

type IndexType = ZodString | ZodNumber | ZodStringFormat | ZodNumberFormat;

/* Main type for lField factory function*/
type LFieldFn = {
  <T extends ZodType>(schema: T): T;

  /* Mark field as unique */
  unique<T extends IndexType>(schema: T): T;

  /* Mark field as indexed */
  index<T extends IndexType>(schema: T): T;

  /* Auto-generated UUID field */
  autouuid(): ReturnType<AutogeneratedImpl["autouuid"]>;

  /* Auto-increment integer field */
  autoincrement(): ReturnType<AutogeneratedImpl["autoincrement"]>;

  /* Default to current date/time */
  now(): ReturnType<AutogeneratedImpl["now"]>;

  /* Default to current date/time, updated automatically */
  updatedAt(): ReturnType<AutogeneratedImpl["updatedAt"]>;

  /* Relation: one item from another list */
  oneFrom(ref: () => void): ReturnType<PopularImpl["oneFrom"]>;

  /* Relation: many items from another list */
  manyFrom(ref: () => void): ReturnType<PopularImpl["manyFrom"]>;

  /* Primary key field factory */
  id: {
    <T extends IndexType>(schema: T): T;
    auto(): ZodD;
  };
};
const AUTO_MARK = z.object({ __auto: z.custom<true>() });

class IdField {
  fn<T extends IndexType>(schema: T) {
    return schema
  }
  auto() {
    return z.uuid().default(() => crypto.randomUUID()).meta({ auto: true, idField: true }).or(AUTO_MARK);
  }
}
/* Field implementation for indexes and constraints */
class FieldImpl {
  unique = <T extends IndexType>(s: T): T => s.meta({ unique: true }) as T;
  index = <T extends IndexType>(s: T): T => s.meta({ index: true }) as T;
}

/* Field implementation for autogenerated values */
class AutogeneratedImpl {
  private mark = z.object({ __auto: z.custom<true>() });

  autouuid = (idField = false) =>
    z.uuid().default(() => crypto.randomUUID()).meta({ autouuid: true, idField }).or(this.mark);

  autoincrement = () =>
    z.number().default(0).meta({ autoincrement: true }).or(this.mark);

  now = () =>
    z.iso
      .datetime()
      .default(() => new Date().toISOString())
      .meta({ now: true })
      .or(this.mark);

  updatedAt = () =>
    z.iso
      .datetime().or(z.null())
      .default(null)
      .meta({ updatedAt: true })
      .or(this.mark);
}

/* Field implementation for relations */
class PopularImpl {
  oneFrom = (ref: () => any) =>
    z.lazy(() => {
      return ref().SItem.meta({
        ref: ref(),
        method: "oneFrom",
      });
    });

  manyFrom = (ref: () => any) =>
    z.lazy(() => {
      return ref().SItem.meta({
        pupolar: {
          ref: ref(),
          method: "manyFrom",
        },
      });
    });
}

/* IdField factory */
function createIdField() {
  const ID = new IdField()
  const id = ID.fn as LFieldFn["id"];
  id.auto =  ID.auto
  return id;
}

/* Factory to create lField function */
function createField(): LFieldFn {
  const fn = (<T extends ZodType>(schema: T) => schema as T) as LFieldFn;
  const auto = new AutogeneratedImpl();
  Object.assign(
    fn,
    new FieldImpl(),
    auto,
    new PopularImpl(),
    { id: createIdField(auto) }
  );
  return fn;
}

// -------------------------
// Export
// -------------------------
export const lField = createField();