import z, {  ZodNumber, ZodNumberFormat, ZodString, ZodStringFormat, ZodType } from "zod/v4";

type IndexType = ZodString | ZodNumber | ZodStringFormat | ZodNumberFormat;

/* Main type for lField factory function*/
type LFieldFn = {
  <T extends ZodType>(schema: T): T;

  /* Mark field as unique */
  unique<T extends IndexType>(schema: T): T;

  /* Mark field as indexed */
  index<T extends IndexType>(schema: T): T;

  /* Auto-generated UUID field */
  autouuid(): ReturnType<AutogeneratedImpl["autouuid"]>;

  /* Auto-increment integer field */
  autoincrement(): ReturnType<AutogeneratedImpl["autoincrement"]>;

  /* Default to current date/time */
  now(): ReturnType<AutogeneratedImpl["now"]>;

  /* Default to current date/time, updated automatically */
  updatedAt(): ReturnType<AutogeneratedImpl["updatedAt"]>;

  /* Relation: one item from another list */
  oneFrom(ref: () => any): ReturnType<PopularImpl["oneFrom"]>;

  /* Relation: many items from another list */
  manyFrom(ref: () => any): ReturnType<PopularImpl["manyFrom"]>;

  /* Primary key field factory */
  id: {
   <T extends IndexType>(schema: T): T;
    autouuid(): ReturnType<AutogeneratedImpl["autouuid"]>;
    autoincrement(): ReturnType<AutogeneratedImpl["autoincrement"]>;
  };
};

/* Field implementation for indexes and constraints */
class FieldImpl {
  unique = <T extends IndexType>(s: T): T => s.meta({ unique: true }) as T;
  index = <T extends IndexType>(s: T): T => s.meta({ index: true }) as T;
}

/* Field implementation for autogenerated values */
class AutogeneratedImpl {
  private mark = z.object({ __auto: z.custom<true>() });

  autouuid = () =>
    z.uuid().default(() => crypto.randomUUID()).meta({ autouuid: true }).or(this.mark);

  autoincrement = () =>
    z.number().default(0).meta({ autoincrement: true }).or(this.mark);

  now = () =>
    z.iso
      .datetime()
      .default(() => new Date().toISOString())
      .meta({ now: true })
      .or(this.mark);

  updatedAt = () =>
    z.iso
      .datetime()
      .default(() => new Date().toISOString())
      .meta({ updatedAt: true })
      .or(this.mark);
}

/* Field implementation for relations */
class PopularImpl {
  oneFrom = (ref: () => any) =>
    z.lazy(() => {
      return ref().SItem.meta({
        ref: ref(),
        method: "oneFrom",
      });
    });

  manyFrom = (ref: () => any) =>
    z.lazy(() => {
      return ref().SItem.meta({
        pupolar: {
          ref: ref(),
          method: "manyFrom",
        },
      });
    });
}

/* IdField factory */
function createIdField(auto: AutogeneratedImpl) {
  const id = (<T extends IndexType >(schema: T): T =>
    schema.meta({ keyPath: true }) as T) as LFieldFn["id"];
  id.autouuid = () => auto.autouuid().meta({ keyPath: true, autouuid: true });
  id.autoincrement = () => auto.autoincrement().meta({ keyPath: true, autoincrement: true });
  return id;
}

/* Factory to create lField function */
function createField(): LFieldFn {
  const fn = (<T extends ZodType>(schema: T) => schema as T) as LFieldFn;
  const auto = new AutogeneratedImpl();
  Object.assign(
    fn,
    new FieldImpl(),
    auto,
    new PopularImpl(),
    { id: createIdField(auto) }
  );
  return fn;
}

// -------------------------
// Export
// -------------------------
export const lField = createField();