import z, { ZodArray, ZodNumber, ZodNumberFormat, ZodObject, ZodRawShape, ZodString, ZodStringFormat, ZodType } from "zod/v4";
import { LRawShape, } from "./schema";
import { schemaRegistry } from "./schema2";

type IndexType = ZodString | ZodNumber | ZodStringFormat | ZodNumberFormat;

/* Main type for lField factory function*/
type LFieldFn = {
  <T extends ZodType>(schema: T): T;

  /* Mark field as unique */
  unique<T extends IndexType>(schema: T): T;

  /* Mark field as indexed */
  index<T extends IndexType>(schema: T): T;

  /* Auto-generated UUID field */
  autouuid(): ReturnType<AutogeneratedImpl["autouuid"]>;

  /* Auto-increment integer field */
  autoincrement(): ReturnType<AutogeneratedImpl["autoincrement"]>;

  /* Default to current date/time */
  now(): ReturnType<AutogeneratedImpl["now"]>;

  /* Default to current date/time, updated automatically */
  updatedAt(): ReturnType<AutogeneratedImpl["updatedAt"]>;

  /* Relation: one item from another list */
  oneFrom<S extends z.ZodObject>(ref?: () => S): ReturnType<PopularImpl["oneFrom"]>

  /* Relation: many items from another list */
  manyFrom<S extends z.ZodObject>(ref?: () => S): ReturnType<PopularImpl["manyFrom"]>;

  /* Primary key field factory */
  id: {
    <T extends IndexType>(schema: T): T;
    autogenerated(): ReturnType<AutogeneratedImpl["autouuid"]>;
  };
};

/* Field implementation for indexes and constraints */
class FieldImpl {
  unique = <T extends IndexType>(s: T): T => s.meta({ unique: true }) as T;
  index = <T extends IndexType>(s: T): T => s.meta({ index: true }) as T;
}

/* Field implementation for autogenerated values */
const AUTO_Mark = z.object({ __auto: z.custom<true>() });
class AutogeneratedImpl {

  autouuid = () =>
    z.uuid().default(() => crypto.randomUUID()).meta({ autouuid: true }).or(AUTO_Mark);

  autoincrement = () =>
    z.number().default(0).meta({ autoincrement: true }).or(AUTO_Mark);

  now = () =>
    z.iso
      .datetime()
      .default(() => new Date().toISOString())
      .meta({ now: true })
      .or(AUTO_Mark);

  updatedAt = () =>

    z.iso
      .datetime()
      .meta({ updatedAt: true })
      .or(z.null().default(() => null))
      .or(AUTO_Mark)

}

/* Field implementation for relations */
class PopularImpl {

  oneFrom<S extends z.ZodObject>(ref?: () => S) {
    let _schema: S | undefined = ref?.();
    
    const zLazy = z.lazy(() => {
      if (!_schema) throw new Error("Schema not set yet");
      return _schema;
    });

    // نضيف method لتحديد schema لاحقاً
    (zLazy as any).from = (schema: S) => {
      _schema = schema;
      return zLazy as unknown as S;
    }

    return zLazy as unknown as z.ZodType<S> & { from: (schema: S) => S }
  }

  manyFrom<S extends z.ZodObject>(ref?: () => S) {
    let _schema: S | undefined = ref?.();

    const zLazy = z.lazy(() => {
      if (!_schema) throw new Error("Schema not set yet");
      return z.array(_schema);
    });

    (zLazy as any).from = (schema: S) => {
      _schema = schema;
      return zLazy as unknown as z.ZodArray<S>;
    }

    return zLazy as unknown as z.ZodArray<S> & { from: (schema: S) => z.ZodArray<S> }
  }
}


/* IdField factory */
function createIdField() {
  const id = (<T extends IndexType>(schema: T): T =>
    schema.meta({ keyPath: true }) as T) as LFieldFn["id"];
  id.autogenerated = () => z.uuid().default(() => crypto.randomUUID()).meta({ auto: true, idField: true }).or(AUTO_Mark);
  return id;
}

/* Factory to create lField function */
function createField(): LFieldFn {
  const fn = (<T extends ZodType>(schema: T) => schema as T) as LFieldFn;
  const auto = new AutogeneratedImpl();
  Object.assign(
    fn,
    new FieldImpl(),
    auto,
    new PopularImpl(),
    { id: createIdField() }
  );
  return fn;
}

// -------------------------
// Export
// -------------------------
export const lField = createField();